# Site settings
title: Environmental Engineering and Health Services
email: info@eehs.co
description: Environmental Engineering and Health Services
url: "http://eehs.co" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
