# Site settings
title: Environmental Engineering and Health Services
email: your-email@domain.com
description: Environmental Engineering and Health Services
url: "http://www.eehs.co" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
